---
title: "Reproducible Research Assignment 1 cserre"
author: "Christian Serre"
date: "December 14, 2014"
output: html_document
---
## Initialization, Get the data
```{r}
setwd("/Volumes/LightRoom 2 Backup/Data Science/Reproducible Data/ReproducibleDataDecAssignment 1")
library(data.table)
library(plyr)
dt<- data.table(read.csv(unz("activity.zip", "activity.csv"), header=T, sep=",", colClasses = c("numeric", "Date", "numeric")))
```
## What is mean total number of steps of steps per day?
### 1. Histogram of Total Number of steps per day  
```{r, echo=TRUE}
dt[is.na(dt)] <- 0
res1<-ddply(dt, c("date"), function(df)sum(df$steps))
hist(res1$V1, main= "Total Number of Steps Taken Each Day", col="red", xlab="Steps")
```

### 2. Mean and Median
  a Mean Steps per day    
```{r, echo=TRUE}
mean(res1$V1, na.rm=T) 
```
  b Median Steps per day  
```{r, echo=TRUE}
median(res1$V1, na.rm=T)
```
## What is the Average Daily Activity Pattern
### 1. Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
```{r, echo=TRUE}
res2<-ddply(dt, c("date","interval"), function(df)mean(df$steps))
plot(res2$interval, res2$V1, type = "l", xlab = "5 minutes interval", ylab = "Steps")
```